import { Inter } from "next/font/google";

import "./globals.css";

import SideMenu from "@/Components/Menu/SideMenu";
import Topbar from "@/Components/TopBar/Topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BLACK-ARCH GAMING",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-hidden`}>
        <main className="p-1 flex h-screen md:p-4 lg:p-6">
          {/* Fixed SideMenu */}
          <div className="fixed h-full w-20">
            <SideMenu />
          </div>

          {/* Fixed Content Area */}
          <div id="sha-2" className="sha-1 rounded-xl ml-24 flex-1 h-full overflow-auto">
            <div className="p-2 h-full rounded-xl flex flex-col">
              {/* Topbar */}
              <div className="flex-shrink-0">
                <Topbar />
              </div>

              {/* Scrollable Content */}
              <div className="flex-1 overflow-auto scrollbar-hide">
                {children}
              </div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
